"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.YEAR = exports.MONTH = exports.WEEK = exports.DAY = exports.TOTAL_AVERAGE = exports.TOTAL_SUM = exports.AVERAGE = exports.SUM = exports.CALCULATE = exports.LTE = exports.GTE = exports.NONE_OF = exports.ANY_OF = exports.EQUALS = exports.BULK = exports.SINGLE = exports.DELETE = exports.GET = exports.PUT = exports.TABLES = exports.FILTER_GROUP = exports.MODULE = exports.NAME = exports.TAG = exports.FILTER = exports.DESCRIPTION = exports.EVENT_TYPE = exports.AMOUNT = exports.DATE = exports.EVENT_ROW = void 0;
const EVENT_ROW = 'eventRow';
exports.EVENT_ROW = EVENT_ROW;
const DATE = 'date';
exports.DATE = DATE;
const AMOUNT = 'amount';
exports.AMOUNT = AMOUNT;
const EVENT_TYPE = 'eventType';
exports.EVENT_TYPE = EVENT_TYPE;
const DESCRIPTION = 'description';
exports.DESCRIPTION = DESCRIPTION;
const FILTER = 'filter';
exports.FILTER = FILTER;
const TAG = 'tag';
exports.TAG = TAG;
const NAME = 'name';
exports.NAME = NAME;
const MODULE = 'module';
exports.MODULE = MODULE;
const FILTER_GROUP = 'filterGroup';
exports.FILTER_GROUP = FILTER_GROUP;
const TABLES = [EVENT_ROW, FILTER, TAG, MODULE, FILTER_GROUP];
exports.TABLES = TABLES;
const PUT = 'put';
exports.PUT = PUT;
const GET = 'get';
exports.GET = GET;
const DELETE = 'delete';
exports.DELETE = DELETE;
const SINGLE = 'single';
exports.SINGLE = SINGLE;
const BULK = 'bulk';
exports.BULK = BULK;
const EQUALS = 'equals';
exports.EQUALS = EQUALS;
const ANY_OF = 'anyOf';
exports.ANY_OF = ANY_OF;
const NONE_OF = "noneOf";
exports.NONE_OF = NONE_OF;
const GTE = 'gte';
exports.GTE = GTE;
const LTE = 'lte';
exports.LTE = LTE;
const CALCULATE = 'calculate';
exports.CALCULATE = CALCULATE;
const SUM = 'sum';
exports.SUM = SUM;
const AVERAGE = 'average';
exports.AVERAGE = AVERAGE;
const TOTAL_SUM = 'totalSum';
exports.TOTAL_SUM = TOTAL_SUM;
const TOTAL_AVERAGE = 'totalAverage';
exports.TOTAL_AVERAGE = TOTAL_AVERAGE;
const DAY = 'day';
exports.DAY = DAY;
const WEEK = 'week';
exports.WEEK = WEEK;
const MONTH = 'month';
exports.MONTH = MONTH;
const YEAR = 'year';
exports.YEAR = YEAR;